import { HISTORICAL_AUM, HISTORICAL_HOLDINGS, type Order, type ObservedBucket, type createAdvEngine } from './adv-migration';
const f=(x:number,d=2)=>x.toLocaleString('en-GB',{maximumFractionDigits:d,minimumFractionDigits:d});
export default function AdvCalibrationPanel({orders,buckets,engine,aums}:{orders:Order[];buckets:ObservedBucket[];engine:ReturnType<typeof createAdvEngine>;aums:number[]}) {
 return <>
  <article className="card table-card"><div className="card-head"><div><h2>Historical joint calibration</h2><p>${f(HISTORICAL_AUM/1e9,1)}bn AUM · {HISTORICAL_HOLDINGS} assumed holdings · one year of parent orders</p></div></div>
   <div className="table-scroll"><table><thead><tr><th>Bucket</th><th>Observed orders</th><th>Fitted orders</th><th>Observed $m</th><th>Fitted $m</th><th>Value error</th></tr></thead><tbody>{buckets.map((b,i)=>{const os=orders.filter(o=>o.bucket===i), count=os.reduce((s,o)=>s+o.count,0),value=os.reduce((s,o)=>s+o.count*o.ticket,0)/1e6;return <tr key={b.label}><td>{b.label}</td><td>{f(b.trades,0)}</td><td>{f(count,2)}</td><td>{f(b.valueUsdMillion,3)}</td><td>{f(value,3)}</td><td>{f(100*(value/b.valueUsdMillion-1),6)}%</td></tr>})}</tbody></table></div>
   <div className="input-foot"><p>ADV is interpolated in log dollars between the supplied percentiles. A broad ticket-size prior (log standard deviation 1.5) is tilted within each bucket to match its observed count and value. Liquidity preference changes that prior, then the model refits. Synthetic weighted orders are not reconstructed trades; stock-count deciles are not imposed as trading shares. This fit is not unique.</p></div>
  </article>
  <article className="card table-card"><div className="card-head"><div><h2>Execution feasibility</h2><p>Required days are uncapped; unfinished dollars remain visible.</p></div></div><div className="table-scroll"><table><thead><tr><th>AUM</th><th>Annual orders</th><th>Annual intended $m</th><th>Required days</th><th>Unfinished notional</th></tr></thead><tbody>{aums.map((a,i)=>{const m=engine.metric(a);return <tr key={i}><td>${f(a,1)}bn</td><td>{f(m.annualOrders,1)}</td><td>{f(m.annualValue/1e6,3)}</td><td>{f(m.avgDays,1)}</td><td>{f(m.unfinished,2)}%</td></tr>})}</tbody></table></div>
  <div className="input-foot"><p>Higher AUM increases ticket sizes. More holdings reduces tickets and increases order frequency; higher turnover increases frequency. Historical turnover is calibrated exactly from $944.475m; the 13.9% scenario default is rounded. Partial completion reduces alpha capture; impact costs apply only to executed notional. Alpha and impact are anchored to the historical portfolio under the selected execution policy. Simultaneous orders in the same stock and changing daily volumes are not identified by these aggregate inputs.</p></div></article>
 </>;
}
